apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkus
  description: Quarkus Archetype for educational purposes
  tags:
    - quarkus
    - archetype
  links:
    - url: https://github.com/ivoair/quarkus
      title: Quarkus Archetype
      icon: github
  annotations:
    backstage.io/techdocs-ref: dir:.  
spec:
  lifecycle: production
  type: archetype
  owner: ivoair
  system: public-websites
